config/routes.rb
AuctionApp::Application.routes.draw do  
  resources :categories, only: [:index, :show]
  resources :items

  root "items#index"
  
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/help', to: 'static_pages#help', as: 'help'
  get '/documentation', to: 'static_pages#documentation', as: 'documentation'
  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  
  default_scope -> { order('name') }
  validates :name, presence: true, uniqueness: true,
                   length: { maximum: 80 }
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  
  default_scope -> { order('created_at DESC') }
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 200 }
  validates :vendor, presence: true
  validates :starting_price, presence: true, 
                             numericality: { greater_than: 0 }
  
  def Item.search(category_id, query)
    # naive database-based implementation 
    if category_id.blank? && query.blank?
      Item.all
    elsif category_id.blank?
      Item.where('name like ? or description like ?', "%#{query}%", "%#{query}%")
    elsif query.blank?
      Item.where('category_id == ?', category_id)
    else
       Item.where('category_id == ? and (name like ? or description like ?)', 
                  category_id, "%#{query}%", "%#{query}%")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_category_options, only: [:new, :create, :index, :edit, :update]
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "New item added."
      redirect_to @item
    else
      render 'new'
    end
  end
  
  def index
    @items = Item.search(params[:category_id], params[:query]).paginate(page: params[:page], per_page: 4)
  end
  
  def show
    @category = Category.find(@item.category_id)
  end
  
  def edit
  end
  
  def update
    if @item.update_attributes(item_params)
      flash[:success] = "Item details updated."
      redirect_to @item
    else
      render 'edit'
    end
  end
  
  def destroy
    @item.destroy
    flash[:success] = "Item deleted."
    redirect_to items_url
  end
  
  private
  
    def item_params
      params.require(:item)
            .permit(:name, :description, :category_id, :vendor, :starting_price)
    end
  
    def set_item
      @item = Item.find(params[:id])
    end
  
    def set_category_options
      @category_options = Category.all.collect { |c| [c.name, c.id] }
      # @category_options = []
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
  
  def contact
  end

  def help
  end
  
  def documentation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_category.html.erb
<li>
  <%= link_to category.name, category %>
</li>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= render @categories %>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>
<p>
  <%= @category.description %>
</p>

app/views/items/_item.html.erb
<li><%= link_to item.name, item %> (<%= item.category.name.singularize %>) 
    <%= number_to_currency(item.starting_price) %></li>
<%# requires a database access for each item - not good! %>

app/views/items/_query_form.html.erb
<%= form_tag items_path, method: 'get' do %>
  <p>
    <%= label_tag :query, "Search for:" %>
    <%= select_tag(:category_id, 
                   options_for_select(@category_options, selected: params[:category_id]),
                   prompt: "Category?") %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= form_for @item do |f| %>
  <%= render 'shared/error_messages', form: f.object %>

  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
 
    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_area :description %></td>
    </tr>

    <tr>
      <td><%= f.label :category_id %></td>
      <td>
        <%= f.select(:category_id, 
                     options_for_select(@category_options, selected: @item.category_id)) %>
      </td>
    </tr>
   
    <tr>
      <td><%= f.label :vendor %></td>
      <td><%= f.text_field :vendor %></td>
    </tr>
  
    <tr>
      <td><%= f.label :starting_price %></td>
      <td><%= f.number_field :starting_price %></td>
    </tr>
  
    <tr>
      <td><%= f.submit "Edit item" %></td>
    </tr>
  </table>

<P>
  <%= link_to "Item details", @item %>
<% end %>

app/views/items/index.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<h1>Search for items</h1>

<%= render 'query_form' %>

<h1>Items</h1>

<%= render @items %>

<p>
<%= will_paginate @items %>

<h1><%= link_to "Add new item", new_item_path %></h1>

app/views/items/new.html.erb
<h1>Add new item</h1>

<%= form_for @item do |f| %>
  <%= render 'shared/error_messages', form: f.object %>

  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
 
    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_area :description %></td>
    </tr>

    <tr>
      <td><%= f.label :category_id %></td>
      <td>
        <%= f.select(:category_id, options_for_select(@category_options)) %>
      </td>
    </tr>
   
    <tr>
      <td> <%= f.label :vendor %></td>
      <td><%= f.text_field :vendor %></td>
    </tr>
  
    <tr>
      <td><%= f.label :starting_price %></td>
      <td><%= f.number_field :starting_price %></td>
    </tr>
  
    <tr>
      <td><%= f.submit "Add item" %></td>
    </tr>
  </table>
<% end %>

app/views/items/show.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<h1>Item: <%= @item.name %></h1>

<p>
<%= @item.description %>
<p>
  Category: <%= link_to @category.name, items_path(category_id: @category.id) %>
<p>
  Vendor: <%= @item.vendor %>
<p>
  Starting price: <%= @item.starting_price %>
 
<p>
<%= link_to 'Edit', edit_item_path(@item) %>
<%= link_to 'Delete', @item, method: :delete, 
                      data: { confirm: "Are you sure you  want to delete '#{@item.name}'?" } %>

app/views/layouts/_footer.html.erb
<footer>
  <span class="address">
  Author: Rodney Topor, January 2014
  </span>
  <span class="footer-list">
    <%= link_to "Documentation", documentation_path %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header">
    <span class="header-icon">
      <%= link_to "Auction app", root_path %> 
    </span>
    <span class="header-list">
      <%= link_to "About", about_path %>
      <%= link_to "Contact", contact_path %>
      <%= link_to "Help", help_path %>
    </span
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <%= yield %>
  <%= render "layouts/footer" %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if form.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      The form contains <%= pluralize(form.errors.count, "error") %>.
      <ul>
      <% form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p>
  This is a very simple online auction app implemented using Ruby on Rails.
  
<p>
  It is a sample solution 
  to Assignment 1 of the 2014 summer semester offering of 2503ICT Web 
  Programming at Griffith University.
  
<p>
  Users may browse items for sale by category, search for items
  by name or description, view details of single items, and offer
  new items for sale.  Vendors are represented simplisticly by name 
  only.  There is no authentication or bidding.
  
<p>
  The solution was implemented by the teacher, Rodney Topor.
  
  

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

<p>Rodney Topor, r.topor@griffith.edu.au, L08 2.12, 3732 1291.</p>

app/views/static_pages/documentation.html.erb
<h1>Documentation</h1>

<p>
  This is a complete implementation of the simple online auction app required 
  for 2503ICT Assignment 1.
  
<p>
  The repository is at https://bitbucket.org/rodney-topor/auction_app.
  
<p>
  To prepare the app for use, install the source code from the repository 
  and (inside the app folder) give the Rails commands
  
<pre>
bundle install
rake db:reset
rake db:populate
</pre>
  
<p>
  The path to the home page is root, /.
  
<p>
  All required features are implemented and appear to work correctly.
  
<p>
  Additional features: The category of each item is a link to all items 
  of that category, the edit page contains a link to the item details page,
  a flash is used to confirm changes,
  and lists are paginated using the gem will_paginate.

<p>
  Implementation notes: I'm not happy with the way the view show.html.erb 
  calls method category of class Item, which does a database access.  
  This doesn't belong in a view.  Headings for item lists are crude.  
  A debug information box has been retained. 

<p>
  Usability testing: A colleague was asked to test the app and noted 
  that the correct category was not shown in the edit form.  This was easily 
  corrected.  He also recommended against putting the new item form on the 
  home page which he said was already busy enough.  He said that links did not 
  stand out enough, so I made all links italic, though this might not help enough.

app/views/static_pages/help.html.erb
<h1>Help</h1>

<p>
The root or home page shows a search form, an item list, and a link to a new item form.
  
<p>
Selecting an item name leads to an item details page.  The category name on the item details 
page is a link to all items in that category.

<p>
The search form allows users to optionally select a category and to optionally give a single term
that occurs in either item names or item descriptions.  If neither is selected, then all items are
returned.
  
<p>
The header contains a link to the home page (top left) and links to about, contact and help
pages (top right).